services:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /home/intermidia/enoe-otavio/Server/log:/var/log # Mapeando o diretório de logs do host para o contêiner
    command:
      - -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: