services:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    depends_on:
      - loki
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /home/intermidia/enoe-otavio/Server/log:/var/log
    command:
      - -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    depends_on:
      - loki
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  mosquitto-exporter:
    image: sapcc/mosquitto-exporter
    container_name: mosquitto-exporter
    ports:
      - "9234:9234"
    environment:
      - BROKER_ENDPOINT=tcp://100.111.36.103:1883
      - MQTT_USER=server
      - MQTT_PASS=server.publisher

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

volumes:
  grafana-storage:
