services:
  postgres:
    build:
      dockerfile: ./Dockerfiledb
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enoe_database
    ports:
      - "5432:5432"
    volumes:
      - ./Database/postgres_configurations:/var/lib/postgresql/data  # Monta o volume no local onde o PostgreSQL armazena dados

